services:
  github-runner:
    build: .
    container_name: github-runner
    restart: unless-stopped
    environment:
      RUNNER_SCOPE: repo
      REPO_URL: ${REPO_URL}
      GH_PAT: ${GH_PAT}
      RUNNER_NAME: docker-runner
      LABELS: docker,self-hosted

    volumes:
      - runner-data:/home/runner/_work

volumes:
  runner-data: